<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="xlh-028" name="Default test" tests="1" failures="1" timestamp="27 Dec 2016 06:03:16 GMT" time="107.666" errors="0">
  <testcase name="chuangyeReleaseLoan" time="105.6" classname="test.apptest.chuangye.AppChuangyeReleaseLoan">
    <failure type="java.lang.StringIndexOutOfBoundsException" message="String index out of range: 5">
      <![CDATA[java.lang.StringIndexOutOfBoundsException: String index out of range: 5
	at java.lang.String.substring(Unknown Source)
	at test.apptest.chuangye.AppChuangyeReleaseLoan.chuangyeReleaseLoan(AppChuangyeReleaseLoan.java:119)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- chuangyeReleaseLoan -->
</testsuite> <!-- Default test -->
