<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="115381" started-at="2016-12-22T09:23:25Z" finished-at="2016-12-22T09:25:21Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="115381" started-at="2016-12-22T09:23:25Z" finished-at="2016-12-22T09:25:21Z">
      <class name="test.apptest.chuangye.AppChuangyeSignUp">
        <test-method status="PASS" signature="springTestContextPrepareTestInstance()[pri:0, instance:test.apptest.chuangye.AppChuangyeSignUp@406199]" name="springTestContextPrepareTestInstance" is-config="true" duration-ms="665" started-at="2016-12-22T17:23:25Z" finished-at="2016-12-22T17:23:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextPrepareTestInstance -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:test.apptest.chuangye.AppChuangyeSignUp@406199]" name="beforeClass" is-config="true" duration-ms="0" started-at="2016-12-22T17:23:26Z" finished-at="2016-12-22T17:23:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="chuangyeSignUp(java.util.Map)[pri:0, instance:test.apptest.chuangye.AppChuangyeSignUp@406199]" name="chuangyeSignUp" duration-ms="114356" started-at="2016-12-22T17:23:26Z" description="活动报名" data-provider="testData" finished-at="2016-12-22T17:25:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{apkPathOfChuangye=D:\autoApp\testAPK\Easyrongchuangye_pre_2_3_1.apk, fundPassword=xlh123456, backPassword=xlh123456, filePath=D:\autotest.pdf, changyeUserName=15000000002, backUserName=zdhcs, fundUserName=lkj123, comments=app自动化测试用评论123，有长度要求超过20个字, activity=自动化测试活动-长期, chuangyePassword=xlh123456, version=v2.3}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at test.apptest.chuangye.AppChuangyeSignUp.chuangyeSignUp(AppChuangyeSignUp.java:133)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:46)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:37)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask$Sync.innerRun(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- chuangyeSignUp -->
        <test-method status="PASS" signature="springTestContextBeforeTestMethod(java.lang.reflect.Method)[pri:0, instance:test.apptest.chuangye.AppChuangyeSignUp@406199]" name="springTestContextBeforeTestMethod" is-config="true" duration-ms="0" started-at="2016-12-22T17:23:26Z" finished-at="2016-12-22T17:23:26Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void test.apptest.chuangye.AppChuangyeSignUp.chuangyeSignUp(java.util.Map) throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextBeforeTestMethod -->
        <test-method status="PASS" signature="springTestContextAfterTestMethod(java.lang.reflect.Method)[pri:0, instance:test.apptest.chuangye.AppChuangyeSignUp@406199]" name="springTestContextAfterTestMethod" is-config="true" duration-ms="1" started-at="2016-12-22T17:25:20Z" finished-at="2016-12-22T17:25:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void test.apptest.chuangye.AppChuangyeSignUp.chuangyeSignUp(java.util.Map) throws java.lang.Exception]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- springTestContextAfterTestMethod -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:test.apptest.chuangye.AppChuangyeSignUp@406199]" name="afterClass" is-config="true" duration-ms="1" started-at="2016-12-22T17:25:21Z" finished-at="2016-12-22T17:25:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- test.apptest.chuangye.AppChuangyeSignUp -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
